# Generated by Django 2.2.2 on 2019-06-05 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_description', models.CharField(max_length=500)),
                ('date_active', models.DateField(default=datetime.datetime(2019, 6, 5, 16, 39, 53, 787613, tzinfo=utc))),
                ('time_active', models.TimeField(default=datetime.datetime(2019, 6, 5, 16, 39, 53, 787634, tzinfo=utc))),
            ],
        ),
    ]
