# Generated by Django 2.2.2 on 2019-06-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('textField', models.TextField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
