# Generated by Django 2.2.2 on 2019-06-07 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0005_remove_postmodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='dateCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
