# Generated by Django 2.2.2 on 2019-06-07 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0006_postmodel_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
