# Generated by Django 2.2.2 on 2019-06-07 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0007_auto_20190607_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='dateCreated',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
